services:
  fake-movie-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "EnterpriseCore"
    ports:
      - "1433:1433"
    restart: always

  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: fake-movie-api
    depends_on:
      - fake-movie-db
    volumes:
      - ./api:/app
    working_dir: /app
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5020"]
    ports:
      - "5020:5020"
    environment:
      ConnectionStrings__FakeMovieDB: "Server=host.docker.internal;Database=FakeMovieDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};Encrypt=False;TrustServerCertificate=True"

  frontend:
    image: denoland/deno:alpine-2.2.5
    container_name: fake-movie-frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["deno", "run", "serve", "--allow-net", "--allow-read", "--allow-env"]
    ports:
      - "8000:8000"
    environment:
      VITE_API_URL: "${VITE_API_URL}"
